version: '3.1'

services:
  project:
    build:
      context: .
    ports:
      - "8080:8080"
    links:
      - pg:pg

  pg:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
